// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: compaction.proto

package compaction

import (
	"fmt"
	"io"
	"math"

	proto "github.com/golang/protobuf/proto"

	_ "github.com/gogo/protobuf/gogoproto"

	_ "github.com/pingcap/kvproto/pkg/coprocessor"

	_ "github.com/pingcap/kvproto/pkg/metapb"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Dipsatch the task request to compact server..
type CompactTaskRequest struct {
	DbId                 string   `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty"`
	StoreId              int64    `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	JobId                int64    `protobuf:"varint,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Input                []byte   `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompactTaskRequest) Reset()         { *m = CompactTaskRequest{} }
func (m *CompactTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CompactTaskRequest) ProtoMessage()    {}
func (*CompactTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_compaction_e934e97986a7e94a, []int{0}
}
func (m *CompactTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompactTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompactTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CompactTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactTaskRequest.Merge(dst, src)
}
func (m *CompactTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *CompactTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompactTaskRequest proto.InternalMessageInfo

func (m *CompactTaskRequest) GetDbId() string {
	if m != nil {
		return m.DbId
	}
	return ""
}

func (m *CompactTaskRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *CompactTaskRequest) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *CompactTaskRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CompactTaskRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_compaction_e934e97986a7e94a, []int{1}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Error.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return m.Size()
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CompactTaskResponse struct {
	Output               []byte   `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompactTaskResponse) Reset()         { *m = CompactTaskResponse{} }
func (m *CompactTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CompactTaskResponse) ProtoMessage()    {}
func (*CompactTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_compaction_e934e97986a7e94a, []int{2}
}
func (m *CompactTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompactTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompactTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CompactTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactTaskResponse.Merge(dst, src)
}
func (m *CompactTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *CompactTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompactTaskResponse proto.InternalMessageInfo

func (m *CompactTaskResponse) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *CompactTaskResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*CompactTaskRequest)(nil), "compaction.CompactTaskRequest")
	proto.RegisterType((*Error)(nil), "compaction.Error")
	proto.RegisterType((*CompactTaskResponse)(nil), "compaction.CompactTaskResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CompactService service

type CompactServiceClient interface {
	Compact(ctx context.Context, in *CompactTaskRequest, opts ...grpc.CallOption) (*CompactTaskResponse, error)
}

type compactServiceClient struct {
	cc *grpc.ClientConn
}

func NewCompactServiceClient(cc *grpc.ClientConn) CompactServiceClient {
	return &compactServiceClient{cc}
}

func (c *compactServiceClient) Compact(ctx context.Context, in *CompactTaskRequest, opts ...grpc.CallOption) (*CompactTaskResponse, error) {
	out := new(CompactTaskResponse)
	err := c.cc.Invoke(ctx, "/compaction.CompactService/compact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CompactService service

type CompactServiceServer interface {
	Compact(context.Context, *CompactTaskRequest) (*CompactTaskResponse, error)
}

func RegisterCompactServiceServer(s *grpc.Server, srv CompactServiceServer) {
	s.RegisterService(&_CompactService_serviceDesc, srv)
}

func _CompactService_Compact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactServiceServer).Compact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compaction.CompactService/Compact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactServiceServer).Compact(ctx, req.(*CompactTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompactService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compaction.CompactService",
	HandlerType: (*CompactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "compact",
			Handler:    _CompactService_Compact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compaction.proto",
}

func (m *CompactTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompactTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.DbId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.DbId)))
		i += copy(dAtA[i:], m.DbId)
	}
	if m.StoreId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.StoreId))
	}
	if m.JobId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.JobId))
	}
	if len(m.Address) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Address)))
		i += copy(dAtA[i:], m.Address)
	}
	if len(m.Input) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Input)))
		i += copy(dAtA[i:], m.Input)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.Code))
	}
	if len(m.Msg) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Msg)))
		i += copy(dAtA[i:], m.Msg)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *CompactTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompactTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.Error.Size()))
		n1, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Output) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Output)))
		i += copy(dAtA[i:], m.Output)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintCompaction(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CompactTaskRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.DbId)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.StoreId != 0 {
		n += 1 + sovCompaction(uint64(m.StoreId))
	}
	if m.JobId != 0 {
		n += 1 + sovCompaction(uint64(m.JobId))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	l = len(m.Input)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Error) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovCompaction(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CompactTaskResponse) Size() (n int) {
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovCompaction(uint64(l))
	}
	l = len(m.Output)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCompaction(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCompaction(x uint64) (n int) {
	return sovCompaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CompactTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompactTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompactTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DbId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DbId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreId", wireType)
			}
			m.StoreId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			m.JobId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Input", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Input = append(m.Input[:0], dAtA[iNdEx:postIndex]...)
			if m.Input == nil {
				m.Input = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCompaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCompaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CompactTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompactTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompactTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Output = append(m.Output[:0], dAtA[iNdEx:postIndex]...)
			if m.Output == nil {
				m.Output = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCompaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCompaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCompaction
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCompaction
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCompaction(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCompaction = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCompaction   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("compaction.proto", fileDescriptor_compaction_e934e97986a7e94a) }

var fileDescriptor_compaction_e934e97986a7e94a = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0xd9, 0x0f, 0x16, 0x3e, 0x46, 0x62, 0x60, 0x40, 0x53, 0x39, 0x54, 0xd2, 0x8b, 0x5c,
	0xac, 0x09, 0xbe, 0x81, 0xc6, 0x03, 0x89, 0xa7, 0xd5, 0x78, 0xd4, 0xb4, 0xdd, 0x4d, 0x53, 0x08,
	0x4c, 0xdd, 0x5d, 0x78, 0x09, 0x5f, 0xc0, 0x47, 0xf2, 0xe8, 0x23, 0x98, 0xfa, 0x22, 0xa6, 0xdb,
	0x1a, 0x30, 0xc6, 0xd3, 0xce, 0xff, 0x3f, 0x33, 0xbf, 0x99, 0xcc, 0x42, 0x3f, 0xa1, 0x55, 0x1e,
	0x25, 0x36, 0xa3, 0x75, 0x98, 0x6b, 0xb2, 0x84, 0xb0, 0x73, 0xc6, 0xa3, 0x94, 0x52, 0x72, 0xf6,
	0x45, 0x19, 0x55, 0x15, 0xe3, 0x41, 0x52, 0x7a, 0x89, 0x32, 0x86, 0x74, 0x6d, 0xf5, 0x56, 0xca,
	0x46, 0x79, 0x5c, 0xa9, 0xe0, 0x85, 0x01, 0x5e, 0x57, 0x94, 0xfb, 0xc8, 0x2c, 0x85, 0x7a, 0xde,
	0x28, 0x63, 0x71, 0x08, 0x5c, 0xc6, 0x4f, 0x99, 0xf4, 0xd8, 0x84, 0x4d, 0xbb, 0xa2, 0x25, 0xe3,
	0xb9, 0xc4, 0x13, 0xf8, 0x6f, 0x2c, 0x69, 0x55, 0xfa, 0xff, 0x26, 0x6c, 0xda, 0x14, 0x1d, 0xa7,
	0xe7, 0x12, 0x8f, 0xa0, 0xbd, 0x20, 0xd7, 0xd0, 0x74, 0x09, 0xbe, 0xa0, 0xb2, 0xc3, 0x83, 0x4e,
	0x24, 0xa5, 0x56, 0xc6, 0x78, 0x2d, 0x07, 0xfa, 0x96, 0x38, 0x02, 0x9e, 0xad, 0xf3, 0x8d, 0xf5,
	0xf8, 0x84, 0x4d, 0x7b, 0xa2, 0x12, 0xc1, 0x39, 0xf0, 0x1b, 0xad, 0x49, 0x23, 0x42, 0x2b, 0x21,
	0xa9, 0xdc, 0x78, 0x2e, 0x5c, 0x8c, 0x7d, 0x68, 0xae, 0x4c, 0xea, 0x26, 0x77, 0x45, 0x19, 0x06,
	0x0f, 0x30, 0xfc, 0xb1, 0xbb, 0xc9, 0x69, 0x6d, 0x14, 0x9e, 0x01, 0x57, 0x25, 0xc5, 0x95, 0x1e,
	0xcc, 0x06, 0xe1, 0xde, 0xe1, 0x1c, 0x5e, 0x54, 0x79, 0x3c, 0x86, 0x36, 0x6d, 0xec, 0x6e, 0x8b,
	0x5a, 0xcd, 0x1e, 0xe1, 0xb0, 0xe6, 0xde, 0x29, 0xbd, 0xcd, 0x12, 0x85, 0xb7, 0xd0, 0xa9, 0x21,
	0xe8, 0xef, 0xe3, 0x7e, 0x9f, 0x6e, 0x7c, 0xfa, 0x67, 0xbe, 0x5a, 0x2f, 0x68, 0x5c, 0x05, 0x6f,
	0x85, 0xcf, 0xde, 0x0b, 0x9f, 0x7d, 0x14, 0x3e, 0x7b, 0xfd, 0xf4, 0x1b, 0xd0, 0x27, 0x9d, 0x86,
	0x36, 0x5b, 0x6e, 0xc3, 0xe5, 0xd6, 0x7d, 0x4c, 0xdc, 0x76, 0xcf, 0xe5, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x66, 0xa6, 0xcd, 0x64, 0xf6, 0x01, 0x00, 0x00,
}
