// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: compaction.proto

package compaction

import (
	"fmt"
	"io"
	"math"

	proto "github.com/golang/protobuf/proto"

	_ "github.com/gogo/protobuf/gogoproto"

	_ "github.com/pingcap/kvproto/pkg/coprocessor"

	_ "github.com/pingcap/kvproto/pkg/metapb"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobStatus int32

const (
	JobStatus_Running       JobStatus = 0
	JobStatus_FallbackLocal JobStatus = 1
	JobStatus_Finished      JobStatus = 2
	JobStatus_Fail          JobStatus = 3
)

var JobStatus_name = map[int32]string{
	0: "Running",
	1: "FallbackLocal",
	2: "Finished",
	3: "Fail",
}
var JobStatus_value = map[string]int32{
	"Running":       0,
	"FallbackLocal": 1,
	"Finished":      2,
	"Fail":          3,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_compaction_c8cc8dc8f817672f, []int{0}
}

// Dipsatch the task request to compact server..
type StartCompactRequest struct {
	DbId                 string   `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty"`
	DbSessionId          string   `protobuf:"bytes,2,opt,name=db_session_id,json=dbSessionId,proto3" json:"db_session_id,omitempty"`
	StoreId              int64    `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	JobId                int64    `protobuf:"varint,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Input                []byte   `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartCompactRequest) Reset()         { *m = StartCompactRequest{} }
func (m *StartCompactRequest) String() string { return proto.CompactTextString(m) }
func (*StartCompactRequest) ProtoMessage()    {}
func (*StartCompactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_compaction_c8cc8dc8f817672f, []int{0}
}
func (m *StartCompactRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StartCompactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StartCompactRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *StartCompactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartCompactRequest.Merge(dst, src)
}
func (m *StartCompactRequest) XXX_Size() int {
	return m.Size()
}
func (m *StartCompactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartCompactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartCompactRequest proto.InternalMessageInfo

func (m *StartCompactRequest) GetDbId() string {
	if m != nil {
		return m.DbId
	}
	return ""
}

func (m *StartCompactRequest) GetDbSessionId() string {
	if m != nil {
		return m.DbSessionId
	}
	return ""
}

func (m *StartCompactRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *StartCompactRequest) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *StartCompactRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StartCompactRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_compaction_c8cc8dc8f817672f, []int{1}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Error.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return m.Size()
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type QueryCompactionRequest struct {
	DbId                 string   `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty"`
	DbSessionId          string   `protobuf:"bytes,2,opt,name=db_session_id,json=dbSessionId,proto3" json:"db_session_id,omitempty"`
	StoreId              int64    `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	JobId                int64    `protobuf:"varint,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCompactionRequest) Reset()         { *m = QueryCompactionRequest{} }
func (m *QueryCompactionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCompactionRequest) ProtoMessage()    {}
func (*QueryCompactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_compaction_c8cc8dc8f817672f, []int{2}
}
func (m *QueryCompactionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCompactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCompactionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *QueryCompactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCompactionRequest.Merge(dst, src)
}
func (m *QueryCompactionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCompactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCompactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCompactionRequest proto.InternalMessageInfo

func (m *QueryCompactionRequest) GetDbId() string {
	if m != nil {
		return m.DbId
	}
	return ""
}

func (m *QueryCompactionRequest) GetDbSessionId() string {
	if m != nil {
		return m.DbSessionId
	}
	return ""
}

func (m *QueryCompactionRequest) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *QueryCompactionRequest) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *QueryCompactionRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CompactionResponse struct {
	Status               JobStatus `protobuf:"varint,1,opt,name=status,proto3,enum=compaction.JobStatus" json:"status,omitempty"`
	Error                *Error    `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Output               []byte    `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CompactionResponse) Reset()         { *m = CompactionResponse{} }
func (m *CompactionResponse) String() string { return proto.CompactTextString(m) }
func (*CompactionResponse) ProtoMessage()    {}
func (*CompactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_compaction_c8cc8dc8f817672f, []int{3}
}
func (m *CompactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CompactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactionResponse.Merge(dst, src)
}
func (m *CompactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *CompactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompactionResponse proto.InternalMessageInfo

func (m *CompactionResponse) GetStatus() JobStatus {
	if m != nil {
		return m.Status
	}
	return JobStatus_Running
}

func (m *CompactionResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CompactionResponse) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func init() {
	proto.RegisterType((*StartCompactRequest)(nil), "compaction.StartCompactRequest")
	proto.RegisterType((*Error)(nil), "compaction.Error")
	proto.RegisterType((*QueryCompactionRequest)(nil), "compaction.QueryCompactionRequest")
	proto.RegisterType((*CompactionResponse)(nil), "compaction.CompactionResponse")
	proto.RegisterEnum("compaction.JobStatus", JobStatus_name, JobStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CompactService service

type CompactServiceClient interface {
	StartCompact(ctx context.Context, in *StartCompactRequest, opts ...grpc.CallOption) (*CompactionResponse, error)
	QueryCompactionStatus(ctx context.Context, in *QueryCompactionRequest, opts ...grpc.CallOption) (*CompactionResponse, error)
}

type compactServiceClient struct {
	cc *grpc.ClientConn
}

func NewCompactServiceClient(cc *grpc.ClientConn) CompactServiceClient {
	return &compactServiceClient{cc}
}

func (c *compactServiceClient) StartCompact(ctx context.Context, in *StartCompactRequest, opts ...grpc.CallOption) (*CompactionResponse, error) {
	out := new(CompactionResponse)
	err := c.cc.Invoke(ctx, "/compaction.CompactService/StartCompact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactServiceClient) QueryCompactionStatus(ctx context.Context, in *QueryCompactionRequest, opts ...grpc.CallOption) (*CompactionResponse, error) {
	out := new(CompactionResponse)
	err := c.cc.Invoke(ctx, "/compaction.CompactService/QueryCompactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CompactService service

type CompactServiceServer interface {
	StartCompact(context.Context, *StartCompactRequest) (*CompactionResponse, error)
	QueryCompactionStatus(context.Context, *QueryCompactionRequest) (*CompactionResponse, error)
}

func RegisterCompactServiceServer(s *grpc.Server, srv CompactServiceServer) {
	s.RegisterService(&_CompactService_serviceDesc, srv)
}

func _CompactService_StartCompact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCompactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactServiceServer).StartCompact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compaction.CompactService/StartCompact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactServiceServer).StartCompact(ctx, req.(*StartCompactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactService_QueryCompactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCompactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactServiceServer).QueryCompactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compaction.CompactService/QueryCompactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactServiceServer).QueryCompactionStatus(ctx, req.(*QueryCompactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompactService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compaction.CompactService",
	HandlerType: (*CompactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCompact",
			Handler:    _CompactService_StartCompact_Handler,
		},
		{
			MethodName: "QueryCompactionStatus",
			Handler:    _CompactService_QueryCompactionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compaction.proto",
}

func (m *StartCompactRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StartCompactRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.DbId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.DbId)))
		i += copy(dAtA[i:], m.DbId)
	}
	if len(m.DbSessionId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.DbSessionId)))
		i += copy(dAtA[i:], m.DbSessionId)
	}
	if m.StoreId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.StoreId))
	}
	if m.JobId != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.JobId))
	}
	if len(m.Address) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Address)))
		i += copy(dAtA[i:], m.Address)
	}
	if len(m.Input) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Input)))
		i += copy(dAtA[i:], m.Input)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.Code))
	}
	if len(m.Msg) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Msg)))
		i += copy(dAtA[i:], m.Msg)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *QueryCompactionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCompactionRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.DbId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.DbId)))
		i += copy(dAtA[i:], m.DbId)
	}
	if len(m.DbSessionId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.DbSessionId)))
		i += copy(dAtA[i:], m.DbSessionId)
	}
	if m.StoreId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.StoreId))
	}
	if m.JobId != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.JobId))
	}
	if len(m.Address) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Address)))
		i += copy(dAtA[i:], m.Address)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *CompactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompactionResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.Status))
	}
	if m.Error != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(m.Error.Size()))
		n1, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Output) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintCompaction(dAtA, i, uint64(len(m.Output)))
		i += copy(dAtA[i:], m.Output)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintCompaction(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *StartCompactRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.DbId)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	l = len(m.DbSessionId)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.StoreId != 0 {
		n += 1 + sovCompaction(uint64(m.StoreId))
	}
	if m.JobId != 0 {
		n += 1 + sovCompaction(uint64(m.JobId))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	l = len(m.Input)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Error) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovCompaction(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *QueryCompactionRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.DbId)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	l = len(m.DbSessionId)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.StoreId != 0 {
		n += 1 + sovCompaction(uint64(m.StoreId))
	}
	if m.JobId != 0 {
		n += 1 + sovCompaction(uint64(m.JobId))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CompactionResponse) Size() (n int) {
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovCompaction(uint64(m.Status))
	}
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovCompaction(uint64(l))
	}
	l = len(m.Output)
	if l > 0 {
		n += 1 + l + sovCompaction(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCompaction(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCompaction(x uint64) (n int) {
	return sovCompaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StartCompactRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StartCompactRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StartCompactRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DbId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DbId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DbSessionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DbSessionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreId", wireType)
			}
			m.StoreId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			m.JobId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Input", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Input = append(m.Input[:0], dAtA[iNdEx:postIndex]...)
			if m.Input == nil {
				m.Input = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCompaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCompaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCompactionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCompactionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCompactionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DbId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DbId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DbSessionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DbSessionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreId", wireType)
			}
			m.StoreId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			m.JobId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCompaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CompactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (JobStatus(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCompaction
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Output = append(m.Output[:0], dAtA[iNdEx:postIndex]...)
			if m.Output == nil {
				m.Output = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCompaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCompaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCompaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCompaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCompaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCompaction
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCompaction
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCompaction(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCompaction = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCompaction   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("compaction.proto", fileDescriptor_compaction_c8cc8dc8f817672f) }

var fileDescriptor_compaction_c8cc8dc8f817672f = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0x36, 0xb1, 0x93, 0x4e, 0xd2, 0xca, 0x99, 0x36, 0x55, 0xc8, 0xc1, 0x44, 0xbe, 0x10,
	0x21, 0x35, 0x48, 0xe1, 0x0f, 0x88, 0x88, 0x14, 0xc4, 0xa5, 0xce, 0x19, 0x55, 0xb6, 0x77, 0x65,
	0xb6, 0x49, 0x3c, 0x66, 0x77, 0x1d, 0x89, 0x3b, 0x1f, 0xc1, 0x85, 0x7f, 0xe0, 0x1b, 0x38, 0x71,
	0xe4, 0x13, 0x50, 0xf8, 0x11, 0xe4, 0xb5, 0x29, 0x16, 0x54, 0xe2, 0xca, 0xc9, 0x33, 0xef, 0x8d,
	0x9f, 0xde, 0xbe, 0xd9, 0x05, 0x2f, 0xa1, 0x7d, 0x1e, 0x25, 0x46, 0x52, 0x36, 0xcf, 0x15, 0x19,
	0x42, 0xf8, 0x8d, 0x4c, 0x2e, 0x53, 0x4a, 0xc9, 0xc2, 0xcf, 0xca, 0xaa, 0x9a, 0x98, 0x0c, 0x93,
	0x12, 0x4b, 0x84, 0xd6, 0xa4, 0x6a, 0x68, 0xb0, 0x17, 0x26, 0xca, 0xe3, 0xaa, 0x0b, 0x3e, 0x33,
	0xb8, 0xd8, 0x98, 0x48, 0x99, 0x65, 0x25, 0x15, 0x8a, 0x77, 0x85, 0xd0, 0x06, 0x2f, 0xc0, 0xe1,
	0xf1, 0xad, 0xe4, 0x63, 0x36, 0x65, 0xb3, 0xd3, 0xb0, 0xc3, 0xe3, 0x35, 0xc7, 0x00, 0xce, 0x78,
	0x7c, 0xab, 0x85, 0xd6, 0x92, 0xb2, 0x92, 0x3c, 0xb1, 0x64, 0x9f, 0xc7, 0x9b, 0x0a, 0x5b, 0x73,
	0x7c, 0x04, 0x3d, 0x6d, 0x48, 0x89, 0x92, 0x6e, 0x4f, 0xd9, 0xac, 0x1d, 0x76, 0x6d, 0xbf, 0xe6,
	0x38, 0x02, 0xf7, 0x8e, 0xac, 0x68, 0xc7, 0x12, 0xce, 0x1d, 0x95, 0xaa, 0x63, 0xe8, 0x46, 0x9c,
	0x2b, 0xa1, 0xf5, 0xd8, 0xb1, 0x7a, 0xbf, 0x5a, 0xbc, 0x04, 0x47, 0x66, 0x79, 0x61, 0xc6, 0xee,
	0x94, 0xcd, 0x06, 0x61, 0xd5, 0x04, 0xd7, 0xe0, 0xbc, 0x54, 0x8a, 0x14, 0x22, 0x74, 0x12, 0xe2,
	0xc2, 0x5a, 0x74, 0x42, 0x5b, 0xa3, 0x07, 0xed, 0xbd, 0x4e, 0x6b, 0x63, 0x65, 0x19, 0x7c, 0x62,
	0x70, 0x75, 0x53, 0x08, 0xf5, 0x7e, 0x79, 0x1f, 0xd6, 0xff, 0x74, 0xc8, 0xe0, 0x03, 0x03, 0x6c,
	0x5a, 0xd3, 0x39, 0x65, 0x5a, 0xe0, 0x35, 0xb8, 0xda, 0x44, 0xa6, 0xd0, 0xd6, 0xdc, 0xf9, 0x62,
	0x34, 0x6f, 0xac, 0xff, 0x15, 0xc5, 0x1b, 0x4b, 0x86, 0xf5, 0x10, 0x3e, 0x01, 0x47, 0x94, 0xa1,
	0x58, 0xb7, 0xfd, 0xc5, 0xb0, 0x39, 0x6d, 0xd3, 0x0a, 0x2b, 0x1e, 0xaf, 0xc0, 0xa5, 0xc2, 0x94,
	0xa1, 0xb6, 0x6d, 0xa8, 0x75, 0xf7, 0x74, 0x09, 0xa7, 0xf7, 0xaa, 0xd8, 0x87, 0x6e, 0x58, 0x64,
	0x99, 0xcc, 0x52, 0xaf, 0x85, 0x43, 0x38, 0x5b, 0x45, 0xbb, 0x5d, 0x1c, 0x25, 0xdb, 0xd7, 0x94,
	0x44, 0x3b, 0x8f, 0xe1, 0x00, 0x7a, 0x2b, 0x99, 0x49, 0xfd, 0x56, 0x70, 0xef, 0x04, 0x7b, 0xd0,
	0x59, 0x45, 0x72, 0xe7, 0xb5, 0x17, 0x5f, 0x18, 0x9c, 0xd7, 0x67, 0xd9, 0x08, 0x75, 0x90, 0x89,
	0xc0, 0x1b, 0x18, 0x34, 0xef, 0x17, 0x3e, 0x6e, 0x3a, 0x7b, 0xe0, 0xe6, 0x4d, 0xfc, 0xe6, 0xc0,
	0xdf, 0xc1, 0x04, 0x2d, 0x7c, 0x03, 0xa3, 0x3f, 0x16, 0x5a, 0xdb, 0x0e, 0x9a, 0xbf, 0x3e, 0xbc,
	0xf3, 0x7f, 0xcb, 0xbf, 0x08, 0xbe, 0x1e, 0x7d, 0xf6, 0xed, 0xe8, 0xb3, 0xef, 0x47, 0x9f, 0x7d,
	0xfc, 0xe1, 0xb7, 0xc0, 0x23, 0x95, 0xce, 0x8d, 0xdc, 0x1e, 0xe6, 0xdb, 0x83, 0x7d, 0x36, 0xb1,
	0x6b, 0x3f, 0xcf, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x92, 0x84, 0x71, 0x07, 0x94, 0x03, 0x00,
	0x00,
}
